services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file: .env
    volumes:
      - .:/project
      - ./storage:/project/storage
    ports:
      - "8000:8000"

  bot:
    build: .
    command: python -m app.bot
    env_file: .env
    volumes:
      - .:/project
      - ./storage:/project/storage
    depends_on:
      - api
